from __future__ import annotations

from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[2]
TASKS_DIR = ROOT / "tasks"
ITEMS_DIR = TASKS_DIR / "items"

PHASES = {
    "P00": "Normative readiness and repository bootstrap",
    "P01": "Runnable local foundation and CI",
    "P02": "Data model, migrations and synthetic fixtures",
    "P03": "Identity, authorization, action control, audit and outbox",
    "P04": "RAG, LLM gateway, controlled agent, memory and guardrails",
    "P05": "Backend vertical service slices",
    "P06": "Responsive accessible web experiences",
    "P07": "Quality, evaluation and security hardening",
    "P08": "AWS platform, observability, performance and recovery",
    "P09": "Pilot, release and launch",
}

CATALOG: list[dict] = []


def add(
    task_id: str,
    phase: str,
    title: str,
    layer: str,
    context: str,
    dependencies: list[str],
    paths: list[str],
    source: str,
    refs: tuple[list[str], list[str], list[str], list[str], list[str]],
    *,
    approval: list[str] | None = None,
    priority: str = "P1",
    minutes: int = 30,
    network: bool = False,
    paid: bool = False,
    objective: str | None = None,
    conflict: str | None = None,
) -> None:
    CATALOG.append({
        "id": task_id,
        "phase": phase,
        "title": title,
        "layer": layer,
        "context": context,
        "dependencies": dependencies,
        "paths": paths,
        "source": source,
        "refs": refs,
        "approval": approval or [],
        "priority": priority,
        "minutes": minutes,
        "network": network,
        "paid": paid,
        "objective": objective or f"Implement {title.lower()} as one bounded, testable deliverable without changing upstream behavior.",
        "conflict": conflict or f"{context}-{layer}",
    })


# P00 — approvals, dependency baseline and empty-repository bootstrap.
add("TASK-DOC-GOV-001", "P00", "Approve the product requirement baseline for synthetic implementation", "governance", "product-governance", [], ["docs/01-product/README.md", "docs/01-product/requirements.yaml"], "docs/01-product/README.md", ([], ["DEC-017"], [], [], []), approval=["requirement_change"], priority="P0", minutes=45, objective="Reconcile product status and record authorized approval for synthetic implementation without altering requirement semantics.")
add("TASK-DOC-ARCH-001", "P00", "Approve architecture and ADR baseline", "governance", "architecture-governance", [], ["docs/04-architecture/core/README.md", "docs/04-architecture/adr/README.md"], "docs/04-architecture/core/README.md", ([], ["ARCH-001", "ARCH-009", "ADR-001", "ADR-016"], [], [], []), approval=["architecture_change"], priority="P0", minutes=45, objective="Complete human architecture review and record which ARCH and ADR artifacts are approved for implementation.")
add("TASK-DOC-CONTRACT-001", "P00", "Approve API data event and tool contracts", "governance", "contract-governance", [], ["docs/04-architecture/contracts/README.md", "contracts/README.md"], "docs/04-architecture/contracts/README.md", ([], ["ARCH-009"], ["API-BASE-001", "DATA-BASE-001", "EVT-BASE-001"], [], []), approval=["contract_change"], priority="P0", minutes=45, objective="Validate machine contracts against reviewed prose and record human approval without introducing new operations.")
add("TASK-DOC-AI-001", "P00", "Approve AI RAG agent and evaluation baseline", "governance", "ai-governance", [], ["docs/05-ai/README.md", "docs/05-ai/TRACEABILITY.md"], "docs/05-ai/README.md", ([], ["AI-SYS-001", "AI-SYS-012"], ["TOOL-SCHEDULE-001"], ["SEC-CTRL-014"], ["EVAL-METRIC-001", "EVAL-METRIC-015"]), approval=["architecture_change", "security_policy"], priority="P0", minutes=45, objective="Complete human AI-quality and security review and record the approved implementation baseline.")
add("TASK-DOC-SEC-001", "P00", "Approve security privacy and threat baseline", "governance", "security-governance", [], ["docs/06-security/README.md", "docs/06-security/12_SECURITY_CONTROLS.md"], "docs/06-security/README.md", ([], ["ARCH-004"], [], ["SEC-CTRL-001", "SEC-CTRL-025"], ["THR-ABUSE-001", "THR-ABUSE-040"]), approval=["security_policy", "legal_privacy"], priority="P0", minutes=45, objective="Complete human security/privacy review and record approved controls for synthetic implementation only.")
add("TASK-DOC-STACK-001", "P00", "Approve pinned dependency and runtime allowlist", "governance", "dependency-governance", ["TASK-DOC-ARCH-001", "TASK-DOC-SEC-001"], ["docs/09-agent-execution/DEPENDENCY_ALLOWLIST.md"], "docs/04-architecture/core/ARCH-003_COMPONENT_VIEW.md", ([], ["DEC-011", "ARCH-003"], [], ["SEC-SDLC-002", "SEC-SDLC-009"], []), approval=["unapproved_dependency"], priority="P0", minutes=45, network=True, objective="Select supported runtime and library versions, document licenses and security review, and approve an exact dependency allowlist.", conflict="root-config")
add("TASK-REPO-SCAFFOLD-001", "P00", "Create top-level implementation directory skeleton", "repository", "repository", ["TASK-DOC-GOV-001", "TASK-DOC-ARCH-001", "TASK-DOC-CONTRACT-001", "TASK-DOC-AI-001", "TASK-DOC-SEC-001"], ["apps/.gitkeep", "services/.gitkeep", "packages/.gitkeep"], "docs/04-architecture/core/ARCH-003_COMPONENT_VIEW.md", ([], ["ARCH-003", "ADR-001"], [], [], []), priority="P0", minutes=15, objective="Create only the approved top-level implementation directories with no framework or business behavior.", conflict="root-layout")
add("TASK-REPO-CONFIG-001", "P00", "Add safe repository ignore and editor defaults", "repository", "repository", ["TASK-REPO-SCAFFOLD-001"], [".gitignore", ".editorconfig", ".gitattributes"], "docs/00-governance/RESEARCH_AND_DATASET_POLICY.md", ([], ["ARCH-009"], [], ["SEC-CRYPTO-005"], []), priority="P0", minutes=20, objective="Add portable text defaults and ignore generated corpora, local secrets, caches and build output without hiding source artifacts.", conflict="root-config")
add("TASK-TEST-CATALOG-001", "P00", "Wire task catalog validation into preflight", "test", "delivery-governance", ["TASK-REPO-SCAFFOLD-001"], ["scripts/validate-tasks.ps1", "tests/delivery/test_task_catalog.py"], "docs/09-agent-execution/VERIFICATION_EVIDENCE_PROTOCOL.md", ([], ["ARCH-009"], [], ["SEC-SDLC-003"], []), priority="P0", minutes=25, objective="Provide a platform-neutral preflight wrapper and regression test for the task catalog validator.", conflict="delivery-tests")
add("TASK-DOC-DEV-001", "P00", "Document local bootstrap without secrets", "governance", "developer-experience", ["TASK-DOC-STACK-001", "TASK-REPO-CONFIG-001"], ["docs/10-delivery/LOCAL_BOOTSTRAP.md"], "docs/04-architecture/core/ARCH-002_CONTAINER_VIEW.md", ([], ["ARCH-002", "ARCH-003"], [], ["SEC-CRYPTO-005"], []), minutes=30, objective="Document deterministic local bootstrap, validation and shutdown steps using synthetic data and placeholder configuration only.")

# P01 — local runtimes, build and CI.
add("TASK-REPO-PYTHON-001", "P01", "Create pinned Python workspace manifest", "repository", "python-toolchain", ["TASK-DOC-STACK-001", "TASK-REPO-SCAFFOLD-001"], ["pyproject.toml", "uv.lock"], "docs/04-architecture/core/ARCH-003_COMPONENT_VIEW.md", ([], ["ARCH-003"], [], ["SEC-SDLC-002", "SEC-SDLC-009"], []), priority="P0", conflict="python-lock")
add("TASK-REPO-WEB-001", "P01", "Create pinned web workspace manifest", "repository", "web-toolchain", ["TASK-DOC-STACK-001", "TASK-REPO-SCAFFOLD-001"], ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml"], "docs/04-architecture/adr/ADR-003_NEXTJS_FASTAPI_SPLIT.md", ([], ["ADR-003"], [], ["SEC-SDLC-002", "SEC-SDLC-009"], []), priority="P0", conflict="web-lock")
add("TASK-API-BOOT-001", "P01", "Create FastAPI application factory", "api", "bootstrap", ["TASK-REPO-PYTHON-001"], ["services/api/src/campus247/bootstrap/app.py", "tests/api/test_app_boot.py"], "docs/04-architecture/core/ARCH-003_COMPONENT_VIEW.md", ([], ["ARCH-002", "ARCH-003"], ["API-CONV-001"], [], []), priority="P0")
add("TASK-WORKER-BOOT-001", "P01", "Create worker process bootstrap", "worker", "bootstrap", ["TASK-REPO-PYTHON-001"], ["services/worker/src/campus247_worker/main.py", "tests/worker/test_worker_boot.py"], "docs/04-architecture/core/ARCH-002_CONTAINER_VIEW.md", ([], ["ARCH-002", "ADR-001"], ["EVT-BASE-001"], [], []), priority="P0")
add("TASK-WEB-BOOT-001", "P01", "Create Next.js application shell", "web", "web-shell", ["TASK-REPO-WEB-001"], ["apps/web/package.json", "apps/web/src/app/layout.tsx", "apps/web/src/app/page.tsx"], "docs/04-architecture/adr/ADR-003_NEXTJS_FASTAPI_SPLIT.md", (["REQ-F-GOV-001"], ["ADR-003"], [], [], []), priority="P0", conflict="web-shell")
add("TASK-REPO-ENV-001", "P01", "Define validated non-secret environment settings", "application", "configuration", ["TASK-API-BOOT-001"], ["services/api/src/campus247/bootstrap/settings.py", ".env.example", "tests/unit/test_settings.py"], "docs/04-architecture/core/ARCH-008_INTEGRATION_AND_LLM_BOUNDARIES.md", ([], ["ARCH-008"], [], ["SEC-CRYPTO-005"], []), priority="P0", conflict="root-config")
add("TASK-INFRA-LOCAL-001", "P01", "Add local PostgreSQL pgvector compose service", "infrastructure", "local-platform", ["TASK-REPO-CONFIG-001"], ["compose.yaml", "infra/local/postgres/init.sql", "tests/platform/test_compose_postgres.py"], "docs/04-architecture/adr/ADR-004_POSTGRES_PGVECTOR_REDIS_ROLES.md", ([], ["ADR-004"], [], ["SEC-DATA-001"], []), priority="P0", conflict="local-compose")
add("TASK-INFRA-LOCAL-002", "P01", "Add local Redis compose service", "infrastructure", "local-platform", ["TASK-INFRA-LOCAL-001"], ["compose.yaml", "tests/platform/test_compose_redis.py"], "docs/04-architecture/adr/ADR-004_POSTGRES_PGVECTOR_REDIS_ROLES.md", ([], ["ADR-004", "ARCH-007"], [], [], []), priority="P1", conflict="local-compose")
add("TASK-API-HEALTH-001", "P01", "Implement liveness endpoint", "api", "operations", ["TASK-API-BOOT-001"], ["services/api/src/campus247/presentation/health.py", "tests/api/test_health_live.py"], "docs/04-architecture/core/ARCH-002_CONTAINER_VIEW.md", ([], ["ARCH-002"], ["API-BASE-001"], ["SEC-ARCH-013"], []), priority="P0")
add("TASK-API-HEALTH-002", "P01", "Implement bounded readiness endpoint", "api", "operations", ["TASK-API-HEALTH-001", "TASK-REPO-ENV-001"], ["services/api/src/campus247/presentation/health.py", "tests/api/test_health_ready.py"], "docs/04-architecture/core/ARCH-002_CONTAINER_VIEW.md", ([], ["ARCH-002", "ARCH-007"], [], ["SEC-ARCH-013"], []), priority="P0")
add("TASK-TEST-CI-001", "P01", "Create offline lint type and unit CI job", "test", "continuous-integration", ["TASK-REPO-PYTHON-001", "TASK-REPO-WEB-001", "TASK-TEST-CATALOG-001"], [".github/workflows/ci.yaml", "scripts/ci-preflight.ps1"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-009"], [], ["SEC-SDLC-003"], []), priority="P0", conflict="ci-workflow")
add("TASK-TEST-BOUNDARY-001", "P01", "Add architecture import-boundary test", "test", "architecture-conformance", ["TASK-API-BOOT-001", "TASK-WORKER-BOOT-001"], ["tests/architecture/test_import_boundaries.py", "tests/architecture/layers.yaml"], "docs/04-architecture/core/ARCH-003_COMPONENT_VIEW.md", ([], ["ARCH-003", "ARCH-CHECK-003"], [], [], []), priority="P0")

# P02 — contracts, persistence and deterministic fixtures.
add("TASK-TEST-SCHEMA-001", "P02", "Compile every JSON Schema contract", "test", "contracts", ["TASK-DOC-CONTRACT-001", "TASK-REPO-PYTHON-001"], ["tests/contracts/test_json_schemas.py"], "docs/04-architecture/contracts/README.md", ([], ["ARCH-CHECK-004"], ["DATA-BASE-001"], ["SEC-CTRL-006"], []), priority="P0")
add("TASK-TEST-OPENAPI-001", "P02", "Validate OpenAPI and referenced schemas", "test", "contracts", ["TASK-TEST-SCHEMA-001"], ["tests/contracts/test_openapi.py"], "docs/04-architecture/contracts/README.md", ([], ["ARCH-CHECK-004"], ["API-BASE-002"], [], []), priority="P0")
add("TASK-TEST-ASYNCAPI-001", "P02", "Validate AsyncAPI event contract", "test", "contracts", ["TASK-TEST-SCHEMA-001"], ["tests/contracts/test_asyncapi.py"], "docs/04-architecture/contracts/EVENT_CONTRACTS.md", ([], ["ADR-008"], ["EVT-BASE-001"], [], []), priority="P0")
add("TASK-DATA-KERNEL-001", "P02", "Implement shared IDs timestamps and error values", "domain", "shared-kernel", ["TASK-REPO-PYTHON-001", "TASK-TEST-SCHEMA-001"], ["services/api/src/campus247/domain/shared/values.py", "tests/unit/shared/test_values.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", ([], ["ARCH-003"], ["API-CONV-004", "API-CONV-005"], [], []), priority="P0")
add("TASK-DB-BASE-001", "P02", "Create database engine and transaction unit", "database", "persistence", ["TASK-REPO-ENV-001", "TASK-INFRA-LOCAL-001"], ["services/api/src/campus247/infrastructure/db.py", "tests/integration/test_db_connection.py"], "docs/04-architecture/adr/ADR-004_POSTGRES_PGVECTOR_REDIS_ROLES.md", ([], ["ADR-004", "ARCH-003"], [], ["SEC-CRYPTO-003"], []), priority="P0", conflict="db-foundation")
add("TASK-DB-MIG-001", "P02", "Initialize additive migration framework", "database", "persistence", ["TASK-DB-BASE-001"], ["services/api/alembic.ini", "services/api/migrations/env.py", "tests/integration/test_migration_bootstrap.py"], "docs/04-architecture/core/ARCH-002_CONTAINER_VIEW.md", ([], ["ARCH-002", "ADR-004"], [], [], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-IDENTITY-001", "P02", "Add identity and role-binding migration", "database", "identity", ["TASK-DB-MIG-001"], ["services/api/migrations/versions/0001_identity.py", "tests/integration/test_identity_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ARCH-004"], ["DATA-DIC-001", "DATA-DIC-004"], ["SEC-AUTHZ-002"], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-KNOWLEDGE-001", "P02", "Add knowledge source version and chunk migration", "database", "knowledge", ["TASK-DB-IDENTITY-001"], ["services/api/migrations/versions/0002_knowledge.py", "tests/integration/test_knowledge_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ADR-004", "ADR-005"], ["DATA-DIC-030", "DATA-DIC-033"], ["SEC-CTRL-012"], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-CONVERSATION-001", "P02", "Add conversation message and handover migration", "database", "conversation", ["TASK-DB-KNOWLEDGE-001"], ["services/api/migrations/versions/0003_conversation.py", "tests/integration/test_conversation_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ARCH-004"], ["DATA-DIC-020", "DATA-DIC-022"], ["PRIV-RET-002"], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-ACTION-001", "P02", "Add preview confirmation and idempotency migration", "database", "action-control", ["TASK-DB-CONVERSATION-001"], ["services/api/migrations/versions/0004_action.py", "tests/integration/test_action_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ADR-016", "ARCH-006"], ["DATA-DIC-040", "API-IDEM-001"], ["SEC-CTRL-008"], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-TICKET-001", "P02", "Add ticket and immutable ticket-event migration", "database", "ticket", ["TASK-DB-ACTION-001"], ["services/api/migrations/versions/0005_ticket.py", "tests/integration/test_ticket_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ARCH-004"], ["DATA-DIC-011", "DATA-DIC-012"], [], []), priority="P0", conflict="db-migration-head")
add("TASK-DB-DOCREQ-001", "P02", "Add document-request migration", "database", "document-request", ["TASK-DB-TICKET-001"], ["services/api/migrations/versions/0006_document_request.py", "tests/integration/test_document_request_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ARCH-004"], ["DATA-DIC-013"], [], []), priority="P1", conflict="db-migration-head")
add("TASK-DB-BOOKING-001", "P02", "Add room and booking migration", "database", "booking", ["TASK-DB-DOCREQ-001"], ["services/api/migrations/versions/0007_booking.py", "tests/integration/test_booking_schema.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", ([], ["ARCH-004"], ["DATA-DIC-014", "DATA-DIC-015"], [], []), priority="P1", conflict="db-migration-head")
add("TASK-DB-OUTBOX-001", "P02", "Add audit outbox and processed-event migration", "database", "audit-outbox", ["TASK-DB-BOOKING-001"], ["services/api/migrations/versions/0008_audit_outbox.py", "tests/integration/test_outbox_schema.py"], "docs/04-architecture/adr/ADR-008_TRANSACTIONAL_OUTBOX_AND_SQS.md", ([], ["ADR-008", "ARCH-006"], ["EVT-BASE-001"], ["SEC-AUDIT-013"], []), priority="P0", conflict="db-migration-head")
add("TASK-DATA-SEED-001", "P02", "Generate deterministic synthetic identities", "data", "synthetic-data", ["TASK-DB-IDENTITY-001"], ["packages/synthetic/src/identities.py", "packages/synthetic/tests/test_identities.py", "packages/synthetic/samples/identities.json"], "docs/05-ai/SYNTHETIC_DATA_STRATEGY.md", ([], ["DEC-004"], ["INT-DATA-001", "INT-DATA-002"], ["PRIV-DPIA-001"], []), priority="P0")
add("TASK-DATA-SEED-002", "P02", "Generate deterministic service records", "data", "synthetic-data", ["TASK-DATA-SEED-001", "TASK-DB-OUTBOX-001"], ["packages/synthetic/src/services.py", "packages/synthetic/tests/test_services.py", "packages/synthetic/samples/services.json"], "docs/05-ai/SYNTHETIC_DATA_STRATEGY.md", ([], ["DEC-004"], ["INT-DATA-001"], ["PRIV-DPIA-001"], []), priority="P1")

# P03 — trusted identity, authorization, action safety and async reliability.
add("TASK-API-IDENTITY-001", "P03", "Define provider-neutral identity context port", "application", "identity", ["TASK-DATA-KERNEL-001", "TASK-DOC-SEC-001"], ["services/api/src/campus247/ports/identity.py", "tests/unit/identity/test_identity_context.py"], "docs/06-security/06_AUTHENTICATION_AND_ENTRA_MIGRATION.md", ([], ["ADR-015", "ARCH-008"], ["INT-IDP-001"], ["SEC-AUTHN-001"], []), approval=["authentication"], priority="P0")
add("TASK-API-IDENTITY-002", "P03", "Implement synthetic signed-session identity adapter", "integration", "identity", ["TASK-API-IDENTITY-001", "TASK-DATA-SEED-001"], ["services/api/src/campus247/infrastructure/identity/mock.py", "tests/integration/identity/test_mock_identity.py"], "docs/06-security/06_AUTHENTICATION_AND_ENTRA_MIGRATION.md", ([], ["ADR-015"], ["INT-IDP-001"], ["SEC-AUTHN-002", "SEC-AUTHN-003"], []), approval=["authentication", "cryptography"], priority="P0")
add("TASK-API-IDENTITY-003", "P03", "Add identity middleware and trusted request context", "api", "identity", ["TASK-API-IDENTITY-002", "TASK-API-BOOT-001"], ["services/api/src/campus247/presentation/identity.py", "tests/api/test_identity_middleware.py"], "docs/06-security/01_SECURITY_ARCHITECTURE.md", ([], ["ARCH-004"], ["API-CONV-007"], ["SEC-ARCH-001", "SEC-AUTHZ-002"], []), approval=["authentication", "authorization"], priority="P0")
add("TASK-API-POLICY-001", "P03", "Define explicit authorization decision port", "application", "policy", ["TASK-API-IDENTITY-001"], ["services/api/src/campus247/ports/policy.py", "tests/unit/policy/test_policy_contract.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", ([], ["ARCH-004"], [], ["SEC-AUTHZ-001", "SEC-AUTHZ-014"], []), approval=["authorization"], priority="P0")
add("TASK-API-POLICY-002", "P03", "Implement student ownership policies", "domain", "policy", ["TASK-API-POLICY-001"], ["services/api/src/campus247/domain/policy/student.py", "tests/unit/policy/test_student_policy.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", ([], ["ARCH-004"], [], ["SEC-AUTHZ-002", "SEC-AUTHZ-005"], []), approval=["authorization"], priority="P0")
add("TASK-API-POLICY-003", "P03", "Implement staff queue-scope policies", "domain", "policy", ["TASK-API-POLICY-001"], ["services/api/src/campus247/domain/policy/staff.py", "tests/unit/policy/test_staff_policy.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", ([], ["ARCH-004"], [], ["SEC-AUTHZ-003", "SEC-AUTHZ-004"], []), approval=["authorization"], priority="P0")
add("TASK-API-ACTION-001", "P03", "Implement immutable action preview value", "domain", "action-control", ["TASK-DATA-KERNEL-001", "TASK-DB-ACTION-001"], ["services/api/src/campus247/domain/action/preview.py", "tests/unit/action/test_preview.py"], "docs/05-ai/TOOL_USE_POLICY.md", ([], ["ADR-016", "ARCH-006"], ["API-IDEM-003"], ["SEC-CTRL-008"], []), approval=["security_policy"], priority="P0")
add("TASK-API-ACTION-002", "P03", "Implement actor payload and expiry-bound confirmation token", "domain", "action-control", ["TASK-API-ACTION-001"], ["services/api/src/campus247/domain/action/confirmation.py", "tests/unit/action/test_confirmation.py"], "docs/06-security/07_CRYPTOGRAPHY_AND_SECRETS.md", ([], ["ADR-016"], ["API-IDEM-003"], ["SEC-CRYPTO-010"], []), approval=["cryptography", "security_policy"], priority="P0")
add("TASK-API-ACTION-003", "P03", "Implement durable idempotency reservation ledger", "application", "action-control", ["TASK-API-ACTION-001", "TASK-DB-ACTION-001"], ["services/api/src/campus247/application/action/idempotency.py", "tests/integration/action/test_idempotency.py"], "docs/04-architecture/contracts/PAGINATION_AND_IDEMPOTENCY.md", ([], ["ARCH-006"], ["API-IDEM-001", "API-IDEM-007"], ["SEC-CTRL-008"], []), approval=["security_policy"], priority="P0")
add("TASK-API-AUDIT-001", "P03", "Implement minimized append-only audit writer", "application", "audit", ["TASK-DB-OUTBOX-001", "TASK-API-IDENTITY-001"], ["services/api/src/campus247/application/audit/writer.py", "tests/integration/audit/test_writer.py"], "docs/06-security/09_AUDIT_AND_MONITORING.md", ([], ["ARCH-004"], ["EVT-BASE-001"], ["SEC-AUDIT-001", "SEC-AUDIT-022"], []), approval=["security_policy"], priority="P0")
add("TASK-WORKER-OUTBOX-001", "P03", "Implement concurrent-safe outbox relay claim", "worker", "audit-outbox", ["TASK-DB-OUTBOX-001", "TASK-WORKER-BOOT-001"], ["services/worker/src/campus247_worker/outbox/relay.py", "tests/integration/outbox/test_relay_claim.py"], "docs/04-architecture/adr/ADR-008_TRANSACTIONAL_OUTBOX_AND_SQS.md", ([], ["ADR-008", "ARCH-006"], ["EVT-BASE-001"], [], []), priority="P0")
add("TASK-WORKER-EVENT-001", "P03", "Implement processed-event duplicate guard", "worker", "audit-outbox", ["TASK-DB-OUTBOX-001", "TASK-WORKER-BOOT-001"], ["services/worker/src/campus247_worker/events/idempotency.py", "tests/integration/outbox/test_duplicate_delivery.py"], "docs/04-architecture/contracts/EVENT_CONTRACTS.md", ([], ["ADR-008"], ["EVT-BASE-001"], [], []), priority="P0")
add("TASK-TEST-AUTHZ-001", "P03", "Add cross-user and wrong-role negative policy suite", "test", "policy", ["TASK-API-POLICY-002", "TASK-API-POLICY-003"], ["tests/security/test_authorization_matrix.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", ([], ["ARCH-004"], [], ["SEC-AUTHZ-001", "SEC-AUTHZ-014"], ["THR-ABUSE-001", "THR-ABUSE-018"]), priority="P0")
add("TASK-TEST-ACTION-001", "P03", "Add confirmation tamper replay and expiry suite", "test", "action-control", ["TASK-API-ACTION-002", "TASK-API-ACTION-003"], ["tests/security/test_action_confirmation.py"], "docs/06-security/11_ABUSE_CASES.md", ([], ["ADR-016"], ["API-IDEM-001"], ["SEC-CTRL-008"], ["THR-ABUSE-008", "THR-ABUSE-010"]), priority="P0")

# P04 — AI platform, knowledge and controlled graph.
add("TASK-AGENT-LLM-001", "P04", "Define canonical LLM request response and stream types", "agent", "llm-gateway", ["TASK-DOC-AI-001", "TASK-DATA-KERNEL-001"], ["services/api/src/campus247/ports/llm.py", "tests/unit/ai/test_llm_contract.py"], "docs/05-ai/LLM_GATEWAY.md", ([], ["ADR-007", "ARCH-008"], ["INT-LLM-001"], ["AI-SYS-006"], []), priority="P0")
add("TASK-AGENT-LLM-002", "P04", "Implement deterministic fake LLM provider", "agent", "llm-gateway", ["TASK-AGENT-LLM-001"], ["services/api/src/campus247/infrastructure/llm/fake.py", "tests/unit/ai/test_fake_llm.py", "packages/evals/fixtures/llm.yaml"], "docs/05-ai/LLM_GATEWAY.md", ([], ["ADR-007"], ["INT-LLM-001"], ["AI-SYS-007"], ["AI-GW-002"]), priority="P0")
add("TASK-AGENT-LLM-003", "P04", "Implement strict structured-output parser", "agent", "llm-gateway", ["TASK-AGENT-LLM-001", "TASK-TEST-SCHEMA-001"], ["services/api/src/campus247/agent/output_parser.py", "tests/unit/ai/test_output_parser.py"], "docs/05-ai/PROMPT_AND_OUTPUT_GOVERNANCE.md", ([], ["ARCH-008"], ["DATA-BASE-001"], ["AI-SYS-006", "SEC-CTRL-006"], ["EVAL-METRIC-015"]), priority="P0")
add("TASK-AGENT-PROMPT-001", "P04", "Implement versioned prompt registry loader", "agent", "prompt-governance", ["TASK-AGENT-LLM-003"], ["packages/prompts/registry.yaml", "services/api/src/campus247/agent/prompts.py", "tests/unit/ai/test_prompt_registry.py"], "docs/05-ai/PROMPT_AND_OUTPUT_GOVERNANCE.md", ([], ["ARCH-008"], [], ["AI-SYS-008"], []), priority="P0", conflict="prompt-registry")
add("TASK-AGENT-LLM-004", "P04", "Implement gateway budgets timeout and canonical errors", "agent", "llm-gateway", ["TASK-AGENT-LLM-002", "TASK-AGENT-LLM-003"], ["services/api/src/campus247/application/ai/gateway.py", "tests/unit/ai/test_gateway_policy.py"], "docs/05-ai/ROUTING_COST_LATENCY.md", ([], ["ADR-007", "ARCH-007"], ["INT-LLM-001"], ["AI-SYS-009", "SEC-CTRL-017"], []), priority="P0")
add("TASK-AGENT-LLM-005", "P04", "Implement DeepSeek adapter behind canonical gateway", "integration", "llm-gateway", ["TASK-AGENT-LLM-004", "TASK-REPO-ENV-001"], ["services/api/src/campus247/infrastructure/llm/deepseek.py", "tests/contract/ai/test_deepseek_adapter.py"], "docs/05-ai/LLM_GATEWAY.md", ([], ["ADR-007", "ARCH-008"], ["INT-LLM-001"], ["SEC-CTRL-016"], ["AI-GW-003", "AI-GW-009"]), approval=["paid_service", "real_secret_or_data"], priority="P1", network=True, paid=True, objective="Implement the disabled-by-default DeepSeek adapter using approved synthetic fixtures and contract tests; do not perform a live call.")
add("TASK-DATA-CORPUS-001", "P04", "Generate deterministic synthetic knowledge documents", "data", "knowledge", ["TASK-DATA-SEED-001"], ["packages/synthetic/src/knowledge.py", "packages/synthetic/tests/test_knowledge.py", "packages/synthetic/samples/knowledge.yaml"], "docs/05-ai/SYNTHETIC_DATA_STRATEGY.md", ([], ["DEC-004"], ["INT-DATA-001", "INT-DATA-005"], ["SEC-CTRL-012"], ["EVAL-DATA-RAG-001"]), priority="P0")
add("TASK-WORKER-INGEST-001", "P04", "Implement quarantined source acquisition record", "worker", "knowledge", ["TASK-DB-KNOWLEDGE-001", "TASK-WORKER-EVENT-001"], ["services/worker/src/campus247_worker/ingestion/acquire.py", "tests/unit/ingestion/test_acquire.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ARCH-004"], ["RAG-ING-001", "RAG-ING-002"], ["SEC-CTRL-012"], []), priority="P0")
add("TASK-WORKER-INGEST-002", "P04", "Implement normalized text parser with provenance", "worker", "knowledge", ["TASK-WORKER-INGEST-001"], ["services/worker/src/campus247_worker/ingestion/parse.py", "tests/unit/ingestion/test_parse.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["RAG-ING-003", "RAG-ING-005"], ["SEC-CTRL-006"], []), priority="P0")
add("TASK-WORKER-INGEST-003", "P04", "Implement deterministic semantic chunker", "worker", "knowledge", ["TASK-WORKER-INGEST-002"], ["services/worker/src/campus247_worker/ingestion/chunk.py", "tests/unit/ingestion/test_chunk.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["RAG-ING-006", "RAG-ING-007"], [], ["RAG-EVAL-001"]), priority="P0")
add("TASK-WORKER-EMBED-001", "P04", "Implement deterministic fake embedding adapter", "worker", "knowledge", ["TASK-WORKER-INGEST-003"], ["services/worker/src/campus247_worker/ingestion/embed_fake.py", "tests/unit/ingestion/test_embed_fake.py"], "docs/04-architecture/core/ARCH-008_INTEGRATION_AND_LLM_BOUNDARIES.md", ([], ["ARCH-008"], ["INT-EMBED-001"], [], []), priority="P0")
add("TASK-WORKER-INDEX-001", "P04", "Persist version-bound lexical and vector index rows", "worker", "knowledge", ["TASK-WORKER-EMBED-001", "TASK-DB-KNOWLEDGE-001"], ["services/worker/src/campus247_worker/ingestion/index.py", "tests/integration/ingestion/test_index.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-004", "ADR-005"], ["RAG-ING-010"], ["SEC-CTRL-013"], []), priority="P0")
add("TASK-API-RAG-001", "P04", "Implement metadata and effective-date retrieval filter", "application", "retrieval", ["TASK-WORKER-INDEX-001", "TASK-API-POLICY-001"], ["services/api/src/campus247/application/retrieval/filters.py", "tests/unit/retrieval/test_filters.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["DATA-DIC-030"], ["SEC-CTRL-013"], ["RAG-EVAL-005"]), priority="P0")
add("TASK-API-RAG-002", "P04", "Implement bounded PostgreSQL lexical retrieval", "application", "retrieval", ["TASK-API-RAG-001"], ["services/api/src/campus247/infrastructure/retrieval/lexical.py", "tests/integration/retrieval/test_lexical.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["RAG-LEXICAL"], [], ["RAG-EVAL-006"]), priority="P0")
add("TASK-API-RAG-003", "P04", "Implement bounded pgvector retrieval", "application", "retrieval", ["TASK-API-RAG-001"], ["services/api/src/campus247/infrastructure/retrieval/vector.py", "tests/integration/retrieval/test_vector.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["RAG-SEMANTIC"], [], ["RAG-EVAL-001"]), priority="P0")
add("TASK-API-RAG-004", "P04", "Implement deterministic reciprocal-rank fusion", "application", "retrieval", ["TASK-API-RAG-002", "TASK-API-RAG-003"], ["services/api/src/campus247/application/retrieval/fusion.py", "tests/unit/retrieval/test_fusion.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["RAG-FUSION"], [], ["RAG-EVAL-001"]), priority="P0")
add("TASK-AGENT-RERANK-001", "P04", "Implement allowlisted reranker output validation", "agent", "retrieval", ["TASK-API-RAG-004", "TASK-AGENT-LLM-004"], ["services/api/src/campus247/application/retrieval/rerank.py", "tests/unit/retrieval/test_rerank.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ADR-005"], ["AI-PROMPT-RERANK-001"], ["AI-SYS-006"], ["RAG-EVAL-001"]), priority="P1")
add("TASK-API-CITATION-001", "P04", "Implement server-resolved citation bundle", "application", "retrieval", ["TASK-AGENT-RERANK-001"], ["services/api/src/campus247/application/retrieval/citations.py", "tests/unit/retrieval/test_citations.py"], "docs/05-ai/RAG_PIPELINE.md", (["REQ-F-RAG-004"], ["DEC-013"], ["Citation.v1"], ["SEC-CTRL-014"], ["EVAL-METRIC-003", "EVAL-METRIC-004"]), priority="P0")
add("TASK-API-EVIDENCE-001", "P04", "Implement material-claim evidence gate", "application", "retrieval", ["TASK-API-CITATION-001"], ["services/api/src/campus247/application/retrieval/evidence_gate.py", "tests/unit/retrieval/test_evidence_gate.py"], "docs/05-ai/RAG_PIPELINE.md", (["REQ-F-RAG-003"], ["DEC-013"], ["GroundedDraft.v1"], ["AI-SYS-001"], ["EVAL-METRIC-002", "EVAL-METRIC-003"]), priority="P0")
add("TASK-AGENT-STATE-001", "P04", "Define versioned typed agent state", "agent", "agent-orchestration", ["TASK-AGENT-LLM-001", "TASK-API-EVIDENCE-001"], ["services/api/src/campus247/agent/state.py", "tests/unit/agent/test_state.py"], "docs/05-ai/AGENT_STATE_MACHINE.md", ([], ["ADR-006"], ["AgentState.v1"], ["AI-SYS-008"], []), priority="P0")
add("TASK-AGENT-SAFETY-001", "P04", "Implement deterministic sensitive-case rules", "agent", "safety", ["TASK-AGENT-STATE-001"], ["services/api/src/campus247/agent/nodes/safety_rules.py", "tests/unit/agent/test_safety_rules.py"], "docs/05-ai/GUARDRAILS_AND_SENSITIVE_CASES.md", (["REQ-F-HITL-005"], ["DEC-016"], [], ["SEC-CTRL-025"], ["EVAL-DATA-SAFE-001"]), approval=["security_policy"], priority="P0")
add("TASK-AGENT-ROUTE-001", "P04", "Implement validated intent router node", "agent", "agent-orchestration", ["TASK-AGENT-STATE-001", "TASK-AGENT-LLM-004"], ["services/api/src/campus247/agent/nodes/intent.py", "tests/unit/agent/test_intent.py"], "docs/05-ai/AGENT_STATE_MACHINE.md", ([], ["ADR-006"], ["AI-PROMPT-INTENT-001"], ["AI-SYS-006"], ["EVAL-METRIC-007"]), priority="P0")
add("TASK-AGENT-RAG-001", "P04", "Implement retrieval and abstention graph node", "agent", "agent-orchestration", ["TASK-AGENT-ROUTE-001", "TASK-API-EVIDENCE-001"], ["services/api/src/campus247/agent/nodes/retrieve.py", "tests/unit/agent/test_retrieve_node.py"], "docs/05-ai/AGENT_STATE_MACHINE.md", (["REQ-F-RAG-001"], ["ADR-006"], [], ["AI-SYS-001"], ["EVAL-DATA-ABSTAIN-001"]), priority="P0")
add("TASK-AGENT-COMPOSE-001", "P04", "Implement grounded answer composer and output guard", "agent", "agent-orchestration", ["TASK-AGENT-RAG-001", "TASK-AGENT-PROMPT-001"], ["services/api/src/campus247/agent/nodes/compose.py", "tests/unit/agent/test_compose.py"], "docs/05-ai/PROMPT_AND_OUTPUT_GOVERNANCE.md", (["REQ-F-RAG-003"], ["DEC-013"], ["AI-PROMPT-ANSWER-001"], ["SEC-CTRL-014"], ["EVAL-METRIC-002"]), priority="P0")
add("TASK-AGENT-TOOL-001", "P04", "Implement typed tool registry and candidate validator", "agent", "tool-broker", ["TASK-AGENT-STATE-001", "TASK-API-POLICY-001"], ["services/api/src/campus247/agent/tools/registry.py", "tests/unit/agent/test_tool_registry.py"], "docs/05-ai/TOOL_USE_POLICY.md", ([], ["DEC-014"], ["TOOL-SCHEDULE-001", "TOOL-HITL-001"], ["SEC-CTRL-007"], ["EVAL-DATA-TOOL-001"]), approval=["security_policy", "authorization"], priority="P0")
add("TASK-AGENT-TOOL-002", "P04", "Implement write-tool preview and confirmation interrupt", "agent", "tool-broker", ["TASK-AGENT-TOOL-001", "TASK-API-ACTION-003"], ["services/api/src/campus247/agent/tools/write_flow.py", "tests/unit/agent/test_write_flow.py"], "docs/05-ai/TOOL_USE_POLICY.md", ([], ["ADR-006", "ADR-016"], ["TOOL-TICKET-001"], ["SEC-CTRL-008"], ["EVAL-METRIC-010", "EVAL-METRIC-012"]), approval=["security_policy", "authorization"], priority="P0")
add("TASK-AGENT-GRAPH-001", "P04", "Assemble allowlisted LangGraph transitions", "agent", "agent-orchestration", ["TASK-AGENT-SAFETY-001", "TASK-AGENT-COMPOSE-001", "TASK-AGENT-TOOL-002"], ["services/api/src/campus247/agent/graph.py", "tests/unit/agent/test_graph_transitions.py"], "docs/05-ai/AGENT_STATE_MACHINE.md", ([], ["ADR-006"], ["AgentState.v1"], ["AI-SYS-002", "AI-SYS-005"], []), approval=["architecture_change", "security_policy"], priority="P0")
add("TASK-AGENT-CHECKPOINT-001", "P04", "Persist versioned agent checkpoints", "agent", "agent-orchestration", ["TASK-AGENT-GRAPH-001", "TASK-DB-CONVERSATION-001"], ["services/api/src/campus247/infrastructure/agent/checkpoints.py", "tests/integration/agent/test_checkpoints.py"], "docs/05-ai/AGENT_STATE_MACHINE.md", ([], ["ADR-006"], ["AgentState.v1"], ["PRIV-RET-002"], []), priority="P0")
add("TASK-AGENT-MEMORY-001", "P04", "Build bounded conversation context manifest", "agent", "memory", ["TASK-AGENT-CHECKPOINT-001"], ["services/api/src/campus247/application/conversation/context.py", "tests/unit/conversation/test_context.py"], "docs/05-ai/MEMORY_POLICY.md", ([], ["ARCH-004"], ["ConversationSummary.v1"], ["PRIV-FLOW-015"], ["EVAL-DATA-MULTI-001"]), approval=["security_policy", "legal_privacy"], priority="P1")

# P05 — backend vertical slices.
add("TASK-API-SCHEDULE-001", "P05", "Define canonical schedule read port", "application", "schedule", ["TASK-API-IDENTITY-003", "TASK-API-POLICY-002"], ["services/api/src/campus247/ports/schedule.py", "tests/unit/schedule/test_schedule_port.py"], "docs/04-architecture/core/ARCH-008_INTEGRATION_AND_LLM_BOUNDARIES.md", (["REQ-F-SCHEDULE-001"], ["ARCH-008"], ["INT-SIS-001"], ["SEC-AUTHZ-002"], []), priority="P0")
add("TASK-API-SCHEDULE-002", "P05", "Implement deterministic synthetic schedule adapter", "integration", "schedule", ["TASK-API-SCHEDULE-001", "TASK-DATA-SEED-002"], ["services/api/src/campus247/infrastructure/schedule/synthetic.py", "tests/contract/schedule/test_synthetic_adapter.py"], "docs/04-architecture/contracts/INTEGRATION_CATALOG.md", (["REQ-F-SCHEDULE-001"], ["ARCH-008"], ["INT-SIS-001"], ["SEC-AUTHZ-002"], []), priority="P0")
add("TASK-API-SCHEDULE-003", "P05", "Expose own-schedule query endpoint", "api", "schedule", ["TASK-API-SCHEDULE-002"], ["services/api/src/campus247/presentation/schedule.py", "tests/api/test_schedule_me.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", (["REQ-F-SCHEDULE-001"], ["ARCH-006"], ["API-SCHEDULE-001"], ["SEC-AUTHZ-003"], []), approval=["authorization"], priority="P0")
add("TASK-API-CHAT-001", "P05", "Create conversation and append user-message use case", "application", "conversation", ["TASK-DB-CONVERSATION-001", "TASK-API-IDENTITY-003"], ["services/api/src/campus247/application/conversation/messages.py", "tests/integration/conversation/test_messages.py"], "docs/04-architecture/contracts/ENTITY_LIFECYCLES.md", (["REQ-F-CHAT-001"], ["ARCH-004"], ["DATA-LIFE-CONVERSATION"], ["PRIV-RET-002"], []), priority="P0")
add("TASK-API-CHAT-002", "P05", "Expose grounded chat SSE endpoint", "api", "conversation", ["TASK-API-CHAT-001", "TASK-AGENT-CHECKPOINT-001"], ["services/api/src/campus247/presentation/chat.py", "tests/api/test_chat_sse.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", (["REQ-F-CHAT-001"], ["ARCH-006"], ["API-CHAT-001"], ["SEC-CTRL-014"], ["EVAL-DATA-RAG-001"]), priority="P0")
add("TASK-API-TICKET-001", "P05", "Implement ticket aggregate creation transition", "domain", "ticket", ["TASK-DB-TICKET-001", "TASK-API-ACTION-001"], ["services/api/src/campus247/domain/ticket/model.py", "tests/unit/ticket/test_create.py"], "docs/04-architecture/contracts/ENTITY_LIFECYCLES.md", (["REQ-F-TICKET-001"], ["ARCH-004"], ["DATA-LIFE-TICKET"], [], []), priority="P0")
add("TASK-API-TICKET-002", "P05", "Create ticket action preview use case", "application", "ticket", ["TASK-API-TICKET-001", "TASK-API-ACTION-002"], ["services/api/src/campus247/application/ticket/preview.py", "tests/integration/ticket/test_preview.py"], "docs/05-ai/TOOL_USE_POLICY.md", (["REQ-F-TICKET-001"], ["ADR-016"], ["TOOL-TICKET-001"], ["SEC-CTRL-008"], ["EVAL-DATA-TOOL-001"]), approval=["authorization", "security_policy"], priority="P0")
add("TASK-API-TICKET-003", "P05", "Confirm ticket creation exactly once", "application", "ticket", ["TASK-API-TICKET-002", "TASK-API-ACTION-003", "TASK-API-AUDIT-001"], ["services/api/src/campus247/application/ticket/confirm.py", "tests/integration/ticket/test_confirm.py"], "docs/04-architecture/contracts/PAGINATION_AND_IDEMPOTENCY.md", (["REQ-F-TICKET-001"], ["ARCH-006"], ["API-IDEM-001"], ["SEC-CTRL-008"], ["EVAL-METRIC-012"]), approval=["authorization", "security_policy"], priority="P0")
add("TASK-API-TICKET-004", "P05", "Expose ticket preview and confirm endpoints", "api", "ticket", ["TASK-API-TICKET-003"], ["services/api/src/campus247/presentation/tickets.py", "tests/api/test_ticket_write.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", (["REQ-F-TICKET-001"], ["ARCH-006"], ["API-TICKET-001"], ["SEC-AUTHZ-006"], []), approval=["authorization"], priority="P0")
add("TASK-API-TICKET-005", "P05", "Expose owner-scoped ticket read and list", "api", "ticket", ["TASK-API-TICKET-001", "TASK-API-POLICY-002"], ["services/api/src/campus247/presentation/ticket_queries.py", "tests/api/test_ticket_queries.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", (["REQ-F-TICKET-002"], ["ARCH-004"], ["API-PAGE-001"], ["SEC-AUTHZ-003", "SEC-AUTHZ-004"], []), approval=["authorization"], priority="P0")
add("TASK-API-TICKET-006", "P05", "Implement staff ticket transition command", "application", "ticket", ["TASK-API-TICKET-001", "TASK-API-POLICY-003", "TASK-API-AUDIT-001"], ["services/api/src/campus247/application/ticket/transition.py", "tests/integration/ticket/test_staff_transition.py"], "docs/02-service-design/QUEUES_AND_ROUTING.md", (["REQ-F-TICKET-004"], ["ARCH-004"], ["DATA-LIFE-TICKET"], ["SEC-AUTHZ-006"], []), approval=["authorization"], priority="P1")
add("TASK-API-DOCREQ-001", "P05", "Implement document-request aggregate and validation", "domain", "document-request", ["TASK-DB-DOCREQ-001", "TASK-API-ACTION-001"], ["services/api/src/campus247/domain/document_request/model.py", "tests/unit/document_request/test_model.py"], "docs/04-architecture/contracts/ENTITY_LIFECYCLES.md", (["REQ-F-DOC-001"], ["ARCH-004"], ["DATA-LIFE-DOCREQ"], [], []), priority="P1")
add("TASK-API-DOCREQ-002", "P05", "Expose confirmed synthetic document-request flow", "api", "document-request", ["TASK-API-DOCREQ-001", "TASK-API-ACTION-003"], ["services/api/src/campus247/presentation/document_requests.py", "tests/api/test_document_request.py"], "docs/04-architecture/contracts/INTEGRATION_CATALOG.md", (["REQ-F-DOC-001"], ["ARCH-006"], ["INT-DOC-001"], ["SEC-CTRL-008"], []), approval=["authorization", "security_policy"], priority="P1")
add("TASK-API-ROOM-001", "P05", "Implement room availability overlap query", "application", "booking", ["TASK-DB-BOOKING-001"], ["services/api/src/campus247/application/booking/availability.py", "tests/integration/booking/test_availability.py"], "docs/04-architecture/contracts/DATA_DICTIONARY.md", (["REQ-F-ROOM-001"], ["ARCH-004"], ["DATA-DIC-014", "DATA-DIC-015"], [], []), priority="P1")
add("TASK-API-ROOM-002", "P05", "Implement booking conflict-safe aggregate command", "domain", "booking", ["TASK-API-ROOM-001", "TASK-API-ACTION-003"], ["services/api/src/campus247/domain/booking/model.py", "tests/integration/booking/test_reserve.py"], "docs/04-architecture/contracts/ENTITY_LIFECYCLES.md", (["REQ-F-ROOM-005"], ["ARCH-006"], ["INT-ROOM-001"], ["SEC-CTRL-008"], []), approval=["authorization", "security_policy"], priority="P1")
add("TASK-API-ROOM-003", "P05", "Expose room search preview and confirm APIs", "api", "booking", ["TASK-API-ROOM-002"], ["services/api/src/campus247/presentation/rooms.py", "tests/api/test_rooms.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", (["REQ-F-ROOM-005", "REQ-F-ROOM-007"], ["ARCH-006"], ["TOOL-ROOM-001", "TOOL-ROOM-002"], ["SEC-AUTHZ-006"], []), approval=["authorization"], priority="P1")
add("TASK-API-HITL-001", "P05", "Implement minimized handover aggregate", "domain", "handover", ["TASK-DB-CONVERSATION-001", "TASK-API-AUDIT-001"], ["services/api/src/campus247/domain/handover/model.py", "tests/unit/handover/test_model.py"], "docs/02-service-design/HANDOVER_AND_EMERGENCY_PLAYBOOK.md", (["REQ-F-HITL-001", "REQ-F-HITL-004"], ["DEC-016"], ["TOOL-HITL-001"], ["SEC-CTRL-025"], ["EVAL-DATA-SAFE-001"]), approval=["security_policy", "legal_privacy"], priority="P0")
add("TASK-API-HITL-002", "P05", "Create routed handover and truthful receipt", "application", "handover", ["TASK-API-HITL-001", "TASK-API-POLICY-003"], ["services/api/src/campus247/application/handover/create.py", "tests/integration/handover/test_create.py"], "docs/02-service-design/QUEUES_AND_ROUTING.md", (["REQ-F-HITL-002", "REQ-F-HITL-004"], ["ARCH-006"], ["TOOL-HITL-001"], ["SEC-CTRL-025"], []), approval=["authorization", "security_policy"], priority="P0")
add("TASK-API-HITL-003", "P05", "Expose staff handover queue query", "api", "handover", ["TASK-API-HITL-002"], ["services/api/src/campus247/presentation/handovers.py", "tests/api/test_handover_queue.py"], "docs/06-security/05_AUTHORIZATION_MATRIX.md", (["REQ-F-HITL-004"], ["ARCH-004"], ["API-PAGE-001"], ["SEC-AUTHZ-003", "SEC-AUTHZ-004"], []), approval=["authorization"], priority="P1")
add("TASK-API-KNOW-001", "P05", "Implement knowledge version review and publish transition", "application", "knowledge", ["TASK-WORKER-INDEX-001", "TASK-API-POLICY-003"], ["services/api/src/campus247/application/knowledge/publish.py", "tests/integration/knowledge/test_publish.py"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ARCH-006"], ["RAG-ING-009", "RAG-ING-011"], ["SEC-CTRL-012"], []), approval=["authorization", "security_policy"], priority="P1")
add("TASK-API-KNOW-002", "P05", "Expose knowledge source lifecycle endpoints", "api", "knowledge", ["TASK-API-KNOW-001"], ["services/api/src/campus247/presentation/knowledge.py", "tests/api/test_knowledge_admin.py"], "docs/04-architecture/contracts/API_CONVENTIONS.md", ([], ["ARCH-006"], ["API-KNOW-001"], ["SEC-AUTHZ-013"], []), approval=["authorization"], priority="P1")
add("TASK-API-OPS-001", "P05", "Expose machine-readable capability state", "api", "operations", ["TASK-API-HEALTH-002", "TASK-AGENT-LLM-004"], ["services/api/src/campus247/presentation/capabilities.py", "tests/api/test_capabilities.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007"], ["API-OPS-001"], ["SEC-ARCH-013"], []), priority="P1")

# P06 — web UX, one surface/state family per task.
add("TASK-WEB-DESIGN-001", "P06", "Create accessible design tokens and global styles", "web", "design-system", ["TASK-WEB-BOOT-001"], ["apps/web/src/styles/tokens.css", "apps/web/src/app/globals.css", "apps/web/src/styles/tokens.test.ts"], "docs/03-ux/ACCESSIBILITY.md", ([], ["UX-A11Y-001"], [], [], []), priority="P0", conflict="web-design-system")
add("TASK-WEB-SHELL-001", "P06", "Render navigation shell and simulation disclosure", "web", "web-shell", ["TASK-WEB-DESIGN-001"], ["apps/web/src/components/AppShell.tsx", "apps/web/src/components/AppShell.test.tsx"], "docs/03-ux/INFORMATION_ARCHITECTURE.md", (["REQ-F-GOV-001"], ["UX-IA-001"], [], [], []), priority="P0", conflict="web-shell")
add("TASK-WEB-STATE-001", "P06", "Implement shared loading empty error and offline states", "web", "design-system", ["TASK-WEB-DESIGN-001"], ["apps/web/src/components/AsyncState.tsx", "apps/web/src/components/AsyncState.test.tsx"], "docs/03-ux/SYSTEM_STATES_AND_RECOVERY.md", ([], ["UX-STATE-001"], [], [], []), priority="P0", conflict="web-design-system")
add("TASK-WEB-API-001", "P06", "Create typed API client and safe problem mapping", "web", "api-client", ["TASK-TEST-OPENAPI-001", "TASK-REPO-WEB-001"], ["apps/web/src/lib/api/client.ts", "apps/web/src/lib/api/client.test.ts"], "docs/04-architecture/contracts/ERROR_MODEL.md", ([], ["ADR-003"], ["API-ERR-001"], ["SEC-ARCH-003"], []), priority="P0", conflict="openapi-generated")
add("TASK-WEB-CHAT-001", "P06", "Render chat composer and canonical stream states", "web", "conversation", ["TASK-WEB-SHELL-001", "TASK-WEB-API-001", "TASK-API-CHAT-002"], ["apps/web/src/features/chat/ChatPanel.tsx", "apps/web/src/features/chat/ChatPanel.test.tsx"], "docs/03-ux/INTERACTION_SPECIFICATIONS.md", (["REQ-F-CHAT-001"], ["UX-SCR-CHAT-001"], ["API-CHAT-001"], [], []), priority="P0")
add("TASK-WEB-CITE-001", "P06", "Render resolvable citations and evidence drawer", "web", "conversation", ["TASK-WEB-CHAT-001"], ["apps/web/src/features/chat/CitationDrawer.tsx", "apps/web/src/features/chat/CitationDrawer.test.tsx"], "docs/03-ux/TRUST_AND_CITATION_UX.md", (["REQ-F-RAG-004"], ["UX-TRUST-001"], ["Citation.v1"], ["SEC-CTRL-014"], []), priority="P0")
add("TASK-WEB-SCHEDULE-001", "P06", "Render own-schedule view with freshness state", "web", "schedule", ["TASK-WEB-API-001", "TASK-API-SCHEDULE-003"], ["apps/web/src/features/schedule/ScheduleView.tsx", "apps/web/src/features/schedule/ScheduleView.test.tsx"], "docs/03-ux/SCREEN_INVENTORY.md", (["REQ-F-SCHEDULE-001"], ["UX-SCR-SCHEDULE-001"], ["API-SCHEDULE-001"], [], []), priority="P0")
add("TASK-WEB-TICKET-001", "P06", "Render student ticket list and detail", "web", "ticket", ["TASK-WEB-API-001", "TASK-API-TICKET-005"], ["apps/web/src/features/tickets/TicketList.tsx", "apps/web/src/features/tickets/TicketList.test.tsx"], "docs/03-ux/SCREEN_INVENTORY.md", (["REQ-F-TICKET-002"], ["UX-SCR-TICKET-001"], ["API-PAGE-001"], [], []), priority="P0")
add("TASK-WEB-CONFIRM-001", "P06", "Render immutable action preview and explicit confirmation", "web", "action-control", ["TASK-WEB-API-001", "TASK-API-TICKET-004"], ["apps/web/src/features/actions/ActionConfirmation.tsx", "apps/web/src/features/actions/ActionConfirmation.test.tsx"], "docs/03-ux/ACTION_PREVIEW_AND_CONFIRMATION_UX.md", ([], ["UX-ACT-001"], ["ActionPreview.v1"], ["SEC-CTRL-008"], []), approval=["security_policy"], priority="P0")
add("TASK-WEB-DOCREQ-001", "P06", "Render document-request form through confirmation", "web", "document-request", ["TASK-WEB-CONFIRM-001", "TASK-API-DOCREQ-002"], ["apps/web/src/features/documents/DocumentRequestForm.tsx", "apps/web/src/features/documents/DocumentRequestForm.test.tsx"], "docs/03-ux/INTERACTION_SPECIFICATIONS.md", (["REQ-F-DOC-001"], ["UX-SCR-DOCREQ-001"], ["INT-DOC-001"], [], []), priority="P1")
add("TASK-WEB-ROOM-001", "P06", "Render room search conflict and booking states", "web", "booking", ["TASK-WEB-CONFIRM-001", "TASK-API-ROOM-003"], ["apps/web/src/features/rooms/RoomBooking.tsx", "apps/web/src/features/rooms/RoomBooking.test.tsx"], "docs/03-ux/INTERACTION_SPECIFICATIONS.md", (["REQ-F-ROOM-005"], ["UX-SCR-ROOM-001"], ["TOOL-ROOM-002"], [], []), priority="P1")
add("TASK-WEB-HITL-001", "P06", "Render handover preview receipt and unavailable state", "web", "handover", ["TASK-WEB-API-001", "TASK-API-HITL-002"], ["apps/web/src/features/handover/HandoverPanel.tsx", "apps/web/src/features/handover/HandoverPanel.test.tsx"], "docs/03-ux/SYSTEM_STATES_AND_RECOVERY.md", (["REQ-F-HITL-002", "REQ-F-HITL-004"], ["UX-HITL-001"], ["TOOL-HITL-001"], ["SEC-CTRL-025"], []), approval=["security_policy", "legal_privacy"], priority="P0")
add("TASK-WEB-STAFF-001", "P06", "Render scoped staff ticket queue", "web", "ticket", ["TASK-WEB-TICKET-001", "TASK-API-TICKET-006"], ["apps/web/src/features/staff/StaffTicketQueue.tsx", "apps/web/src/features/staff/StaffTicketQueue.test.tsx"], "docs/02-service-design/QUEUES_AND_ROUTING.md", (["REQ-F-TICKET-004"], ["UX-SCR-STAFF-001"], ["API-PAGE-001"], ["SEC-AUTHZ-004"], []), approval=["authorization"], priority="P1")
add("TASK-WEB-KNOW-001", "P06", "Render knowledge review and publish controls", "web", "knowledge", ["TASK-WEB-API-001", "TASK-API-KNOW-002"], ["apps/web/src/features/knowledge/KnowledgeReview.tsx", "apps/web/src/features/knowledge/KnowledgeReview.test.tsx"], "docs/03-ux/SCREEN_INVENTORY.md", ([], ["UX-SCR-KNOW-001"], ["API-KNOW-001"], ["SEC-AUTHZ-013"], []), approval=["authorization"], priority="P1")
add("TASK-WEB-OPS-001", "P06", "Render operational capability and degradation banner", "web", "operations", ["TASK-WEB-SHELL-001", "TASK-API-OPS-001"], ["apps/web/src/features/operations/CapabilityBanner.tsx", "apps/web/src/features/operations/CapabilityBanner.test.tsx"], "docs/03-ux/SYSTEM_STATES_AND_RECOVERY.md", ([], ["UX-STATE-DEGRADED"], ["API-OPS-001"], [], []), priority="P1")
add("TASK-WEB-A11Y-001", "P06", "Add keyboard and accessible-name regression tests", "test", "web-accessibility", ["TASK-WEB-CHAT-001", "TASK-WEB-SCHEDULE-001", "TASK-WEB-CONFIRM-001"], ["apps/web/src/test/accessibility.test.tsx"], "docs/03-ux/ACCESSIBILITY.md", ([], ["UX-A11Y-001"], [], [], []), priority="P0")
add("TASK-WEB-RESPONSIVE-001", "P06", "Add small medium and desktop viewport snapshots", "test", "web-accessibility", ["TASK-WEB-HITL-001", "TASK-WEB-STAFF-001", "TASK-WEB-KNOW-001"], ["apps/web/e2e/responsive.spec.ts", "apps/web/e2e/responsive.snapshots.json"], "docs/03-ux/README.md", ([], ["ASM-005", "UX-A11Y-001"], [], [], []), priority="P1", conflict="shared-snapshots")

# P07 — evaluation and cross-cutting verification.
add("TASK-EVAL-SCHEMA-001", "P07", "Validate eval case run and result schemas", "eval", "evaluation", ["TASK-TEST-SCHEMA-001", "TASK-DOC-AI-001"], ["packages/evals/src/validate.py", "packages/evals/tests/test_schemas.py"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["AI-SYS-007"], [], [], ["EVAL-DATA-RAG-001"]), priority="P0")
add("TASK-EVAL-RAG-001", "P07", "Create reviewed synthetic RAG development sample", "eval", "evaluation", ["TASK-DATA-CORPUS-001", "TASK-EVAL-SCHEMA-001"], ["packages/evals/datasets/rag-dev.yaml", "packages/evals/tests/test_rag_dataset.py"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["DEC-004"], [], [], ["EVAL-DATA-RAG-001"]), priority="P0")
add("TASK-EVAL-SAFE-001", "P07", "Create safety and benign-control development sample", "eval", "safety", ["TASK-EVAL-SCHEMA-001", "TASK-AGENT-SAFETY-001"], ["packages/evals/datasets/safety-dev.yaml", "packages/evals/tests/test_safety_dataset.py"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["DEC-016"], [], ["SEC-CTRL-025"], ["EVAL-DATA-SAFE-001"]), approval=["security_policy", "legal_privacy"], priority="P0")
add("TASK-EVAL-RED-001", "P07", "Materialize deterministic prompt-injection red-team cases", "eval", "security-testing", ["TASK-EVAL-SCHEMA-001", "TASK-AGENT-GRAPH-001"], ["packages/evals/datasets/red-team-dev.yaml", "packages/evals/tests/test_red_team_dataset.py"], "docs/05-ai/RED_TEAM_CATALOG.md", ([], ["ARCH-004"], [], ["SEC-CTRL-023"], ["EVAL-RED-001", "EVAL-RED-036"]), priority="P0")
add("TASK-EVAL-RUNNER-001", "P07", "Implement offline fake-provider evaluation runner", "eval", "evaluation", ["TASK-EVAL-RAG-001", "TASK-EVAL-SAFE-001", "TASK-EVAL-RED-001", "TASK-AGENT-LLM-002"], ["packages/evals/src/runner.py", "packages/evals/tests/test_runner.py"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["AI-SYS-007"], [], [], ["EVAL-METRIC-001", "EVAL-METRIC-015"]), priority="P0")
add("TASK-EVAL-GATE-001", "P07", "Implement hard-zero and threshold regression gate", "eval", "evaluation", ["TASK-EVAL-RUNNER-001"], ["packages/evals/src/gates.py", "packages/evals/tests/test_gates.py", "packages/evals/gates/v1.yaml"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["ARCH-CHECK-008"], [], ["SEC-SDLC-005"], ["EVAL-METRIC-009", "EVAL-METRIC-015"]), approval=["security_policy"], priority="P0")
add("TASK-TEST-CONTRACT-001", "P07", "Run API provider and event contract suite", "test", "contracts", ["TASK-API-CHAT-002", "TASK-API-ROOM-003", "TASK-API-KNOW-002", "TASK-WORKER-EVENT-001"], ["tests/contract/test_contract_suite.py"], "docs/04-architecture/contracts/README.md", ([], ["ARCH-CHECK-004"], ["API-BASE-002", "EVT-BASE-001"], [], []), priority="P0")
add("TASK-TEST-E2E-001", "P07", "Add grounded FAQ browser journey", "test", "end-to-end", ["TASK-WEB-CITE-001", "TASK-EVAL-RAG-001"], ["apps/web/e2e/grounded-faq.spec.ts"], "docs/02-service-design/JOURNEYS_AND_BLUEPRINT.md", (["REQ-F-CHAT-001"], ["UX-TRUST-001"], ["API-CHAT-001"], [], ["EVAL-METRIC-003"]), priority="P0")
add("TASK-TEST-E2E-002", "P07", "Add confirmed ticket browser journey", "test", "end-to-end", ["TASK-WEB-CONFIRM-001", "TASK-WEB-TICKET-001"], ["apps/web/e2e/ticket-confirm.spec.ts"], "docs/03-ux/ACTION_PREVIEW_AND_CONFIRMATION_UX.md", (["REQ-F-TICKET-001"], ["UX-ACT-001"], ["API-TICKET-001"], ["SEC-CTRL-008"], []), priority="P0")
add("TASK-TEST-E2E-003", "P07", "Add sensitive handover browser journey", "test", "end-to-end", ["TASK-WEB-HITL-001", "TASK-EVAL-SAFE-001"], ["apps/web/e2e/handover.spec.ts"], "docs/02-service-design/HANDOVER_AND_EMERGENCY_PLAYBOOK.md", (["REQ-F-HITL-006"], ["UX-HITL-001"], ["TOOL-HITL-001"], ["SEC-CTRL-025"], ["EVAL-METRIC-009"]), approval=["security_policy", "legal_privacy"], priority="P0")
add("TASK-TEST-SEC-001", "P07", "Add secret PII and forbidden-log canary scan", "test", "security-testing", ["TASK-API-AUDIT-001", "TASK-AGENT-LLM-005"], ["tests/security/test_no_sensitive_egress.py", "tests/security/fixtures/canaries.yaml"], "docs/06-security/09_AUDIT_AND_MONITORING.md", ([], ["ARCH-004"], [], ["SEC-CRYPTO-007", "SEC-AUDIT-017"], ["AI-GW-009"]), priority="P0")
add("TASK-TEST-SEC-002", "P07", "Add SSRF and unsafe-link negative suite", "test", "security-testing", ["TASK-WEB-CITE-001", "TASK-AGENT-TOOL-001"], ["tests/security/test_ssrf_and_links.py", "tests/security/fixtures/ssrf.yaml"], "docs/06-security/11_ABUSE_CASES.md", ([], ["ARCH-004"], [], ["SEC-ARCH-009", "SEC-CTRL-005"], ["THR-ABUSE-011", "THR-ABUSE-012"]), priority="P0")
add("TASK-TEST-SEC-003", "P07", "Add knowledge poisoning and quarantine suite", "test", "security-testing", ["TASK-WORKER-INGEST-003", "TASK-API-KNOW-001"], ["tests/security/test_knowledge_poisoning.py", "tests/security/fixtures/poisoned_documents.yaml"], "docs/06-security/11_ABUSE_CASES.md", ([], ["ARCH-004"], [], ["SEC-CTRL-012"], ["THR-ABUSE-005", "THR-ABUSE-006"]), priority="P0")
add("TASK-TEST-SEC-004", "P07", "Add security headers cookie CSRF and CORS suite", "test", "security-testing", ["TASK-API-IDENTITY-003", "TASK-WEB-SHELL-001"], ["tests/security/test_web_boundaries.py"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-004"], [], ["SEC-SDLC-006"], []), priority="P0")
add("TASK-TEST-SUPPLY-001", "P07", "Add lockfile secret SBOM and dependency scan job", "test", "supply-chain", ["TASK-TEST-CI-001", "TASK-REPO-PYTHON-001", "TASK-REPO-WEB-001"], [".github/workflows/security.yaml", "scripts/security-scan.ps1"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-CHECK-006"], [], ["SEC-SDLC-009", "SEC-SDLC-013"], []), approval=["security_policy"], priority="P0", conflict="ci-workflow")
add("TASK-TEST-LOAD-001", "P07", "Create reproducible local load-test harness", "test", "performance", ["TASK-API-CHAT-002", "TASK-API-TICKET-004", "TASK-API-SCHEDULE-003"], ["tests/load/scenarios.py", "tests/load/config.yaml", "tests/load/test_scenario_schema.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007"], [], [], ["ARCH-CHECK-009"]), priority="P1")

# P08 — AWS definitions, telemetry and drills. Definitions do not authorize deployment.
add("TASK-INFRA-CDK-001", "P08", "Create pinned AWS CDK TypeScript application", "infrastructure", "aws-platform", ["TASK-DOC-STACK-001", "TASK-REPO-WEB-001"], ["infra/cdk/package.json", "infra/cdk/bin/app.ts", "infra/cdk/test/app.test.ts"], "docs/04-architecture/adr/ADR-014_AWS_CDK_TYPESCRIPT.md", ([], ["ADR-014", "ARCH-005"], [], ["SEC-SDLC-009"], []), approval=["architecture_change", "paid_service"], priority="P0", conflict="cdk-context")
add("TASK-INFRA-NET-001", "P08", "Define two-AZ VPC and private subnet topology", "infrastructure", "aws-platform", ["TASK-INFRA-CDK-001"], ["infra/cdk/lib/network-stack.ts", "infra/cdk/test/network-stack.test.ts"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005"], [], ["SEC-CTRL-005"], []), approval=["architecture_change", "security_policy", "paid_service"], priority="P0", conflict="aws-network")
add("TASK-INFRA-DATA-001", "P08", "Define encrypted RDS PostgreSQL and backup policy", "infrastructure", "aws-platform", ["TASK-INFRA-NET-001"], ["infra/cdk/lib/database-stack.ts", "infra/cdk/test/database-stack.test.ts"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005", "ADR-004"], [], ["SEC-CRYPTO-003", "SEC-CTRL-020"], []), approval=["security_policy", "paid_service"], priority="P0", conflict="aws-data")
add("TASK-INFRA-CACHE-001", "P08", "Define encrypted Multi-AZ Redis replication group", "infrastructure", "aws-platform", ["TASK-INFRA-NET-001"], ["infra/cdk/lib/cache-stack.ts", "infra/cdk/test/cache-stack.test.ts"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005", "ADR-004"], [], ["SEC-CRYPTO-003"], []), approval=["security_policy", "paid_service"], priority="P1", conflict="aws-data")
add("TASK-INFRA-ASYNC-001", "P08", "Define private S3 knowledge buckets and SQS DLQs", "infrastructure", "aws-platform", ["TASK-INFRA-NET-001"], ["infra/cdk/lib/async-stack.ts", "infra/cdk/test/async-stack.test.ts"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005", "ADR-008"], ["EVT-BASE-001"], ["SEC-CTRL-005", "SEC-CTRL-009"], []), approval=["security_policy", "paid_service"], priority="P0", conflict="aws-async")
add("TASK-INFRA-COMPUTE-001", "P08", "Define private ECS Fargate web API and worker services", "infrastructure", "aws-platform", ["TASK-INFRA-NET-001", "TASK-INFRA-DATA-001", "TASK-INFRA-ASYNC-001"], ["infra/cdk/lib/compute-stack.ts", "infra/cdk/test/compute-stack.test.ts"], "docs/04-architecture/adr/ADR-002_ECS_FARGATE_OVER_KUBERNETES.md", ([], ["ADR-002", "ARCH-005"], [], ["SEC-ARCH-002"], []), approval=["architecture_change", "security_policy", "paid_service"], priority="P0", conflict="aws-compute")
add("TASK-INFRA-EDGE-001", "P08", "Define CloudFront WAF ALB and no-cache routes", "infrastructure", "aws-platform", ["TASK-INFRA-COMPUTE-001"], ["infra/cdk/lib/edge-stack.ts", "infra/cdk/test/edge-stack.test.ts"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005"], [], ["SEC-CTRL-005"], []), approval=["security_policy", "paid_service"], priority="P0", conflict="aws-edge")
add("TASK-INFRA-IAM-001", "P08", "Define per-service least-privilege roles and secret references", "infrastructure", "aws-platform", ["TASK-INFRA-COMPUTE-001", "TASK-INFRA-ASYNC-001"], ["infra/cdk/lib/iam-stack.ts", "infra/cdk/test/iam-stack.test.ts"], "docs/06-security/07_CRYPTOGRAPHY_AND_SECRETS.md", ([], ["ARCH-005"], [], ["SEC-CRYPTO-006", "SEC-AUTHZ-009"], []), approval=["authorization", "security_policy", "cryptography"], priority="P0", conflict="aws-iam")
add("TASK-OPS-OTEL-001", "P08", "Instrument API request and dependency telemetry", "observability", "operations", ["TASK-API-BOOT-001", "TASK-API-AUDIT-001"], ["services/api/src/campus247/bootstrap/telemetry.py", "tests/integration/operations/test_telemetry.py"], "docs/06-security/09_AUDIT_AND_MONITORING.md", ([], ["ARCH-007"], [], ["SEC-AUDIT-017", "SEC-AUDIT-019"], []), approval=["security_policy"], priority="P0")
add("TASK-OPS-METRIC-001", "P08", "Emit AI retrieval and tool quality metrics", "observability", "operations", ["TASK-OPS-OTEL-001", "TASK-AGENT-GRAPH-001"], ["services/api/src/campus247/application/operations/metrics.py", "tests/unit/operations/test_metrics.py"], "docs/05-ai/EVALUATION_PLAN.md", ([], ["ARCH-007"], [], ["SEC-AUDIT-006"], ["EVAL-METRIC-001", "EVAL-METRIC-015"]), approval=["security_policy"], priority="P1")
add("TASK-INFRA-MON-001", "P08", "Define redacted dashboards and actionable alarms", "infrastructure", "aws-platform", ["TASK-INFRA-COMPUTE-001", "TASK-OPS-METRIC-001"], ["infra/cdk/lib/monitoring-stack.ts", "infra/cdk/test/monitoring-stack.test.ts"], "docs/06-security/09_AUDIT_AND_MONITORING.md", ([], ["ARCH-007"], [], ["SEC-AUDIT-018", "SEC-AUDIT-021"], []), approval=["security_policy", "paid_service"], priority="P0", conflict="aws-monitoring")
add("TASK-OPS-COST-001", "P08", "Implement provider budget reservation and hard stop", "operations", "cost-control", ["TASK-AGENT-LLM-004", "TASK-OPS-METRIC-001"], ["services/api/src/campus247/application/operations/budget.py", "tests/integration/operations/test_budget.py"], "docs/05-ai/ROUTING_COST_LATENCY.md", ([], ["ARCH-007"], [], ["SEC-CTRL-017"], [],), approval=["security_policy", "paid_service"], priority="P0")
add("TASK-TEST-PERF-001", "P08", "Benchmark hybrid retrieval recall and latency", "test", "performance", ["TASK-TEST-LOAD-001", "TASK-EVAL-RAG-001", "TASK-API-RAG-004"], ["tests/performance/test_retrieval_benchmark.py", "tests/performance/profiles/retrieval.yaml"], "docs/05-ai/RAG_PIPELINE.md", ([], ["ARCH-007"], [], [], ["RAG-EVAL-001", "RAG-EVAL-008"]), priority="P0")
add("TASK-TEST-PERF-002", "P08", "Run chat ticket and schedule peak-load profile", "test", "performance", ["TASK-TEST-LOAD-001", "TASK-OPS-OTEL-001"], ["tests/performance/test_service_load.py", "tests/performance/profiles/service.yaml"], "docs/00-governance/ASSUMPTIONS_AND_OPEN_QUESTIONS.md", ([], ["ASM-001", "ASM-002", "ARCH-007"], [], [], ["ARCH-CHECK-009"]), priority="P0")
add("TASK-TEST-CHAOS-001", "P08", "Verify Redis loss degrades without corrupting truth", "test", "reliability", ["TASK-INFRA-LOCAL-002", "TASK-API-TICKET-003"], ["tests/chaos/test_redis_loss.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007", "ADR-004"], [], [], []), priority="P0")
add("TASK-TEST-CHAOS-002", "P08", "Verify LLM outage enters approved degraded mode", "test", "reliability", ["TASK-AGENT-LLM-004", "TASK-API-OPS-001"], ["tests/chaos/test_llm_outage.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007"], [], ["AI-SYS-009"], []), priority="P0")
add("TASK-OPS-RESTORE-001", "P08", "Script isolated PostgreSQL restore verification", "operations", "disaster-recovery", ["TASK-INFRA-DATA-001", "TASK-DATA-SEED-002"], ["scripts/dr/verify-postgres-restore.ps1", "tests/operations/test_restore_script.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ADR-012", "ARCH-007"], [], ["SEC-CTRL-020"], []), approval=["security_policy", "paid_service"], priority="P0", conflict="staging-drill")
add("TASK-OPS-DELETION-001", "P08", "Implement simulation retention tombstone worker", "worker", "privacy-lifecycle", ["TASK-DB-CONVERSATION-001", "TASK-WORKER-BOOT-001"], ["services/worker/src/campus247_worker/retention/tombstones.py", "tests/integration/retention/test_tombstones.py"], "docs/06-security/08_RETENTION_AND_DELETION.md", ([], ["ARCH-007"], [], ["PRIV-RET-002", "PRIV-RET-021"], []), approval=["legal_privacy", "security_policy"], priority="P1")

# P09 — pilot, release and human-gated launch.
add("TASK-OPS-FLAG-001", "P09", "Implement capability kill-switch configuration", "operations", "release-control", ["TASK-API-OPS-001", "TASK-REPO-ENV-001"], ["services/api/src/campus247/application/operations/feature_flags.py", "tests/unit/operations/test_feature_flags.py"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007"], [], ["SEC-CTRL-021"], []), approval=["security_policy"], priority="P0")
add("TASK-OPS-DEMO-001", "P09", "Package reproducible synthetic demo seed", "operations", "pilot", ["TASK-DATA-SEED-002", "TASK-DATA-CORPUS-001", "TASK-EVAL-GATE-001"], ["scripts/demo/seed.py", "scripts/demo/manifest.yaml", "tests/operations/test_demo_seed.py"], "docs/05-ai/SYNTHETIC_DATA_STRATEGY.md", ([], ["DEC-004"], ["INT-DATA-001"], ["PRIV-DPIA-001"], []), priority="P0")
add("TASK-DOC-RUNBOOK-001", "P09", "Write degraded-mode operations runbook", "operations", "runbooks", ["TASK-OPS-FLAG-001", "TASK-TEST-CHAOS-002"], ["docs/10-delivery/runbooks/DEGRADED_MODE.md"], "docs/04-architecture/core/ARCH-007_RELIABILITY_SCALABILITY_CACHING.md", ([], ["ARCH-007"], [], ["SEC-IR-010"], []), priority="P0")
add("TASK-DOC-RUNBOOK-002", "P09", "Write backup restore and regional recovery runbook", "operations", "runbooks", ["TASK-OPS-RESTORE-001"], ["docs/10-delivery/runbooks/DISASTER_RECOVERY.md"], "docs/04-architecture/adr/ADR-012_SINGLE_REGION_MULTI_AZ_DR.md", ([], ["ADR-012"], [], ["SEC-CTRL-020"], []), priority="P0")
add("TASK-TEST-PILOT-001", "P09", "Run synthetic pilot acceptance journey pack", "test", "pilot", ["TASK-TEST-E2E-001", "TASK-TEST-E2E-002", "TASK-TEST-E2E-003", "TASK-OPS-DEMO-001"], ["tests/pilot/test_acceptance_pack.py", "tests/pilot/manifest.yaml"], "docs/01-product/PRD.md", ([], ["ARCH-009"], [], [], ["EVAL-METRIC-001", "EVAL-METRIC-015"]), priority="P0", conflict="pilot-environment")
add("TASK-TEST-A11Y-001", "P09", "Run full WCAG 2.2 AA evidence pass", "test", "pilot", ["TASK-WEB-A11Y-001", "TASK-WEB-RESPONSIVE-001", "TASK-TEST-PILOT-001"], ["tests/pilot/test_accessibility.py", "tests/pilot/accessibility-manifest.yaml"], "docs/03-ux/ACCESSIBILITY.md", ([], ["ASM-010", "UX-A11Y-001"], [], [], []), priority="P0", conflict="pilot-environment")
add("TASK-TEST-RELEASE-001", "P09", "Assemble immutable release evidence manifest", "release", "release", ["TASK-TEST-PILOT-001", "TASK-TEST-A11Y-001", "TASK-TEST-SUPPLY-001", "TASK-TEST-PERF-002", "TASK-OPS-RESTORE-001"], ["release/evidence-manifest.yaml", "tests/release/test_evidence_manifest.py"], "docs/09-agent-execution/VERIFICATION_EVIDENCE_PROTOCOL.md", ([], ["ARCH-009"], [], ["SEC-SDLC-007"], []), approval=["security_policy"], priority="P0", conflict="release-manifest")
add("TASK-OPS-STAGING-001", "P09", "Deploy release candidate to isolated synthetic staging", "release", "staging-deploy", ["TASK-INFRA-IAM-001", "TASK-INFRA-EDGE-001", "TASK-INFRA-MON-001", "TASK-TEST-RELEASE-001"], ["release/staging-plan.yaml", "release/staging-result.yaml"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-005"], [], ["SEC-SDLC-006"], []), approval=["paid_service", "security_policy"], priority="P0", network=True, paid=True, conflict="staging-deploy", objective="Execute an approved staging deployment using only synthetic data and record immutable deployment and smoke evidence.")
add("TASK-TEST-SOAK-001", "P09", "Run staging soak failover and alert drill", "test", "staging-deploy", ["TASK-OPS-STAGING-001"], ["release/staging-soak.yaml", "release/staging-alert-drill.yaml"], "docs/04-architecture/core/ARCH-005_DEPLOYMENT_TOPOLOGY.md", ([], ["ARCH-005", "ARCH-007"], [], ["SEC-AUDIT-018", "SEC-CTRL-020"], []), approval=["paid_service", "security_policy"], priority="P0", network=True, paid=True, conflict="staging-deploy")
add("TASK-DOC-LAUNCH-001", "P09", "Close or explicitly block every real-launch prerequisite", "governance", "launch-governance", ["TASK-TEST-SOAK-001", "TASK-TEST-RELEASE-001"], ["release/launch-readiness.yaml"], "docs/00-governance/ASSUMPTIONS_AND_OPEN_QUESTIONS.md", ([], ["OQ-001", "OQ-008", "ARCH-009"], [], ["SEC-SDLC-007"], []), approval=["legal_privacy", "security_policy", "production_deploy"], priority="P0", minutes=45, conflict="release-manifest", objective="Record authoritative closure evidence or an explicit blocker for every OQ and production launch gate; do not fabricate closure.")
add("TASK-OPS-PROD-001", "P09", "Execute approved production deployment and smoke checks", "release", "production-deploy", ["TASK-DOC-LAUNCH-001"], ["release/production-plan.yaml", "release/production-result.yaml"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-005"], [], ["SEC-SDLC-007", "SEC-SDLC-008"], []), approval=["production_deploy", "paid_service", "real_secret_or_data", "legal_privacy", "security_policy"], priority="P0", minutes=45, network=True, paid=True, conflict="production-deploy", objective="Execute only the separately approved production change plan, then record smoke, audit, model, egress and rollback evidence.")
add("TASK-OPS-POSTREL-001", "P09", "Verify post-release controls and rollback readiness", "release", "production-deploy", ["TASK-OPS-PROD-001"], ["release/post-release-verification.yaml"], "docs/06-security/13_SECURE_SDLC_GATES.md", ([], ["ARCH-009"], [], ["SEC-SDLC-008"], []), approval=["production_deploy", "security_policy"], priority="P0", minutes=30, network=True, paid=True, conflict="production-deploy")


def input_for(entry: dict) -> list[dict]:
    inputs = [{"path": "docs/00-governance/DOCUMENT_CONTROL.md", "load": "full"}]
    if entry["source"] != "docs/00-governance/DOCUMENT_CONTROL.md":
        inputs.append({"path": entry["source"], "load": "full"})
    return inputs


def verification_for(entry: dict) -> list[dict]:
    candidates = [path for path in entry["paths"] if path.endswith((".py", ".ts", ".tsx"))]
    test_paths = [path for path in candidates if "test" in Path(path).name.lower() or "/tests/" in path or path.startswith("tests/") or "/e2e/" in path]
    if entry["layer"] == "governance":
        command = "python tasks/tools/validate_catalog.py"
        proves = "Task metadata and dependency catalog remain valid after governance review."
    elif test_paths:
        target = test_paths[-1]
        if target.endswith(".spec.ts"):
            command = f"corepack pnpm --dir apps/web exec playwright test {target}"
        elif target.endswith((".ts", ".tsx")):
            command = f"corepack pnpm --dir apps/web test --run {target}"
        else:
            command = f"python -m pytest -q {target}"
        proves = "The focused positive and failure-path behavior passes."
    elif entry["layer"] == "infrastructure":
        command = "corepack pnpm --dir infra/cdk test -- --runInBand"
        proves = "Infrastructure assertions pass without deploying resources."
    else:
        command = "python -m pytest -q"
        proves = "The relevant automated regression suite passes."
    return [{"command": command, "expected_exit_code": 0, "proves": proves}]


def make_task(entry: dict) -> dict:
    requirements, design, contracts, controls, evals = entry["refs"]
    governance_task = entry["layer"] == "governance"
    forbidden = [".git/**", "tasks/**"] if governance_task else ["docs/**", "contracts/**", ".git/**"]
    sensitivity = "critical" if "production_deploy" in entry["approval"] else "high" if entry["approval"] else "medium" if entry["priority"] == "P0" else "low"
    steps = [
        "Read every input and inspect the nearest existing implementation and test pattern.",
        f"Implement only this objective: {entry['objective']}",
        "Add or update the focused positive and failure-path verification within the allowed scope.",
        "Run every verification command, inspect the scoped diff, and emit schema-valid evidence.",
    ]
    return {
        "schema_version": "1.0",
        "id": entry["id"],
        "phase": entry["phase"],
        "title": entry["title"],
        "status": "draft",
        "objective": entry["objective"],
        "layer": entry["layer"],
        "bounded_context": entry["context"],
        "priority": entry["priority"],
        "estimated_minutes": entry["minutes"],
        "sensitivity": sensitivity,
        "human_approval_required": bool(entry["approval"]),
        "approval_reasons": entry["approval"],
        "traceability": {"requirements": requirements, "design": design, "contracts": contracts, "controls": controls, "evals": evals},
        "dependencies": entry["dependencies"],
        "inputs": input_for(entry),
        "write_scope": {"allowed_paths": entry["paths"], "forbidden_paths": forbidden, "max_files": len(entry["paths"]), "max_added_lines": 220 if len(entry["paths"]) == 3 else 160},
        "preconditions": [
            "Every dependency is accepted and every normative input is approved for this environment.",
            "The orchestrator has confirmed a clean, non-overlapping write lease for this task.",
        ],
        "steps": steps,
        "acceptance_criteria": [
            {"id": f"AC-{entry['id']}-01", "assertion": f"The deliverable satisfies the single objective: {entry['objective']}"},
            {"id": f"AC-{entry['id']}-02", "assertion": "The focused failure or negative path is verified and causes no unauthorized side effect."},
            {"id": f"AC-{entry['id']}-03", "assertion": "The final changed-file set is fully contained by the declared write scope."},
        ],
        "verification": verification_for(entry),
        "evidence_required": ["initial and final git status", "changed-file and diff summary", "commands with exit codes", "acceptance-to-evidence mapping"],
        "recovery": {"strategy": "stop_before_promotion" if entry["layer"] in {"release", "governance"} else "reverse_patch", "steps": ["Keep the change unpromoted and apply a reviewed reverse patch limited to this task if rollback is required."]},
        "stop_conditions": [
            "A required source is missing, conflicting, changed after review or not approved.",
            "Completion requires an unlisted file, dependency, network call, secret or destructive operation.",
            "A required human approval is absent, expired or does not name this task and scope.",
        ],
        "parallelism": {"eligible": entry["conflict"] not in {"db-migration-head", "root-config", "python-lock", "web-lock", "staging-deploy", "production-deploy", "release-manifest"}, "conflict_keys": [entry["conflict"]]},
        "execution_policy": {"max_fix_attempts": 2, "network_access": entry["network"], "paid_services": entry["paid"], "destructive_operations": False},
    }


def write_new(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        handle.write(value)


def main() -> None:
    ids = [entry["id"] for entry in CATALOG]
    if len(ids) != len(set(ids)):
        raise RuntimeError("duplicate task IDs in generator")
    known = set(ids)
    for entry in CATALOG:
        missing = set(entry["dependencies"]) - known
        if missing:
            raise RuntimeError(f"missing dependencies for {entry['id']}: {sorted(missing)}")
        if not 1 <= len(entry["paths"]) <= 3:
            raise RuntimeError(f"invalid write scope size for {entry['id']}")

    tasks = [make_task(entry) for entry in CATALOG]
    for task in tasks:
        write_new(ITEMS_DIR / f"{task['id']}.yaml", yaml.safe_dump(task, sort_keys=False, allow_unicode=True, width=120))

    phases = []
    for phase_id, phase_title in PHASES.items():
        phase_tasks = [task for task in tasks if task["phase"] == phase_id]
        phases.append({
            "id": phase_id,
            "title": phase_title,
            "entry_gate": "All external dependencies are accepted; required source approvals and human approvals are attached.",
            "exit_gate": "Every P0 task in the phase is accepted and phase evidence has no unresolved critical finding.",
            "tasks": [{"id": task["id"], "path": f"tasks/items/{task['id']}.yaml", "title": task["title"], "status": task["status"], "dependencies": task["dependencies"], "human_approval_required": task["human_approval_required"]} for task in phase_tasks],
        })
    index = {"schema_version": "1.0", "catalog": "campus247-v1", "generated_by": "tasks/tools/generate_catalog.py", "task_count": len(tasks), "phases": phases}
    dag = {
        "schema_version": "1.0",
        "max_parallel_tasks": 4,
        "parallel_rule": "Run together only when resolved write scopes and conflict keys are disjoint and all dependencies are accepted.",
        "nodes": [{"id": task["id"], "phase": task["phase"], "dependencies": task["dependencies"], "conflict_keys": task["parallelism"]["conflict_keys"], "human_approval_required": task["human_approval_required"]} for task in tasks],
    }
    write_new(TASKS_DIR / "task-index.yaml", yaml.safe_dump(index, sort_keys=False, allow_unicode=True, width=140))
    write_new(TASKS_DIR / "dag.yaml", yaml.safe_dump(dag, sort_keys=False, allow_unicode=True, width=140))
    print(f"generated {len(tasks)} task files across {len(PHASES)} phases")


if __name__ == "__main__":
    main()
